# Generated by Django 2.1.8 on 2019-12-10 01:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='written_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
