# Generated by Django 2.1.8 on 2019-12-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20191210_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('orange', 'orange'), ('yellow', 'yellow'), ('green', 'green'), ('sky', 'sky'), ('blue', 'blue'), ('purple', 'purple'), ('white', 'white'), ('grey', 'gray'), ('black', 'black')], default='8', max_length=15),
        ),
        migrations.AlterField(
            model_name='story',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('orange', 'orange'), ('yellow', 'yellow')], default='0', max_length=15),
        ),
    ]
