# Generated by Django 2.1.8 on 2019-12-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20191210_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('orange', 'orange'), ('yellow', 'yellow'), ('green', 'green'), ('sky', 'sky'), ('blue', 'blue'), ('purple', 'purple'), ('white', 'white'), ('grey', 'gray'), ('black', 'black')], default='yellow', max_length=15),
        ),
        migrations.AlterField(
            model_name='story',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('orange', 'orange'), ('yellow', 'yellow')], default='orange', max_length=15),
        ),
    ]
