# Generated by Django 2.1.8 on 2019-12-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Num',
        ),
        migrations.AddField(
            model_name='profile',
            name='reg',
            field=models.CharField(default='reg', max_length=20),
        ),
    ]
