# Generated by Django 2.1.8 on 2019-12-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0013_auto_20191213_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('orange', 'orange'), ('yellow', 'yellow'), ('green', 'green'), ('sky', 'sky'), ('blue', 'blue'), ('purple', 'purple'), ('white', 'white'), ('grey', 'gray'), ('black', 'black')], default=('grey', 'gray'), max_length=15),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(default='/maps/upload/logo.png', upload_to='maps/upload'),
        ),
    ]
