# Generated by Django 2.1.8 on 2019-12-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0014_auto_20191213_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('orange', 'orange'), ('yellow', 'yellow'), ('green', 'green'), ('sky', 'sky'), ('blue', 'blue'), ('purple', 'purple'), ('white', 'white'), ('grey', 'gray'), ('black', 'black')], default=('black', 'black'), max_length=15),
        ),
    ]
