# Generated by Django 2.1.8 on 2019-12-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0015_auto_20191213_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(upload_to='maps/upload'),
        ),
    ]
