# Generated by Django 2.1.8 on 2019-12-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0018_auto_20191216_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('orange', 'orange'), ('yellow', 'yellow'), ('green', 'green'), ('brown', 'brown'), ('blue', 'blue'), ('purple', 'purple'), ('white', 'white'), ('grey', 'gray'), ('black', 'black')], default=None, max_length=15),
        ),
    ]
