# Generated by Django 2.1.8 on 2019-12-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0021_auto_20191216_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='region',
            name='color',
            field=models.CharField(choices=[('#f38181', '#f38181'), ('#fce38a', '#fce38a'), ('#eaffd0', '#eaffd0'), ('#95e1d3', '#95e1d3'), ('#0c9463', '#0c9463'), ('#2d334a', '#2d334a'), ('#c7f0db', '#c7f0db'), ('#ef4339', '#ef4339'), ('#fe6845', '#fe6845'), ('#dff6f0', '#dff6f0')], default=('#c7f0db', '#c7f0db'), max_length=15),
        ),
    ]
